### ISSUE TITLE
Documenter could not fetch from remote error

### ISSUE THREAD

**Issue by Mattriks** [Mattriks/CoupledFields.jl#1]
Having an issue with Travis and documenter for this package:
https://travis-ci.org/Mattriks/CoupledFields.
The Linux builds give the same error: "could not fetch from remote", when Travis tries to push the documentation to gh-pages (I have a DOCUMENTER_DEBUG key set).
I can build the docs locally, and I've added the SSH deploy keys as in the [Documenter documentation](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html). The settings/Deploy keys tab in my github repo indicates the documenter ssh key has been used. So what is the issue here? 
My versioninfo is:
```julia
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```
and I'm using `Documenter 0.8.5`.
@MichaelHatherly

**Comment by MichaelHatherly** [comment]
I'd guess it's that `repo` should match actual repo name: https://github.com/Mattriks/CoupledFields/blob/9777e2a15f68f0de830771fa674c359c3590aaba/docs/make.jl#L9, note the `.jl` suffix.

**Comment by Mattriks** [comment]
Success! :relieved: & thanks! - Documenter is a really nice package!

**Comment by MichaelHatherly** [comment]
Great, glad it's working now. (Note for any future issues, best to just open an issue over at Documenter so that other future users who also run into the same problem are more likely to find the solution.)
