### ISSUE TITLE
tag release

### ISSUE THREAD

**Issue by bjarthur** [Mattriks/CoupledFields.jl#7]
i can't install Optim master and CoupledFields 0.1.0 because Compat requirements have a null intersection.  can you please tag a release that includes the new Project.toml that has no dependency on Compat?

**Comment by Mattriks** [comment]
Currently fixing some documentation issues (#8).

**Comment by Mattriks** [comment]
Need to figure out why the new docs aren't deploying from travis now.

**Comment by Mattriks** [comment]
@bjarthur  JuliaRegistries/General#12022
